### PR TITLE
 Update driver_specific_capabilities.en.md

### PR DESCRIPTION
**Pull request by adithyab94**
Update driver_specific_capabilities.en.md to resolve build failure

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Thanks for your PR @adithyab94!
Can you please add the changes also to the translated pages?
`driver_specific_capabilities.es.md` and `driver_specific_capabilities.nl.md`?

**Review by diemol — APPROVED** [review]
Thanks!

**Comment by adithyab94** [comment]
Thanks

**Review by cgoldberg — COMMENTED** [review]
@adithyab94 
you missed an import on the python examples that instantiate a driver:

`from selenium import webdriver`

**Pull request merged**
