### PR TITLE
Documented support with python code examples

### PR DESCRIPTION
**Pull request by liushilive**
# MOUSE AND KEYBOARD ACTIONS IN DETAIL

* find_element_by_id
* click
* ActionChains
* move_to_element
* send_keys
* clear

### CODE REVIEW

**Comment by diemol** [comment]
@lmtierney would you like to review the Python part?

**Comment by lmtierney** [comment]
LGTM. @liushilive can you rebase? There have been some changes since you submitted this.

**Comment by liushilive** [comment]
> LGTM。@ liliilive可以改变吗？自提交此内容以来，已发生一些变化。

You can safely add.

**Comment by lmtierney** [comment]
@liushilive thank you!

**Pull request merged**
