### PR TITLE
Update 02_Getting_Started_with_WebDriver.md

### PR DESCRIPTION
**Pull request by friscodelrosario**
little-known locator strategy

### CODE REVIEW

**Comment by andreastt** [comment]
I'm not sure if edge cases should be covered in the getting started guide.  Should this perhaps go somewhere else?

**Comment by davehunt** [comment]
> I'm not sure if edge cases should be covered in the getting started guide. Should this perhaps go somewhere else?

Yeah, perhaps we need a troubleshooting section? New chapter? What do you think, @santiycr?

**Comment by santiycr** [comment]
A troubleshooting section at the end makes sense to me. Having users go through edge case docs while trying to learn the basics sounds like a bad idea.

**Comment by andreastt** [comment]
@friscodelrosario, do you want to make the appropriate changes?

**Comment by mmerrell** [comment]
I'll be glad to take a shot at it if @friscodelrosario doesn't have time

**Comment by andreastt** [comment]
I'd be happy for someone to redo this patch, but because the branch has undergone some maintenance work it must needs rebasing.  I'd suggest sending us a new patch would be easier than rebasing this one, so I'm closing this ticket.

**Pull request closed without merging**
