### PR TITLE
selenium-html-runner 'quick guide' page created.

### PR DESCRIPTION
**Pull request by MilanMasek**
This Closes #4153, Closes SeleniumHQ/selenium#4153.

### CODE REVIEW

**Comment by foutoucour** [comment]
Thank you for the documentation!
Any eta on merge?

**Comment by MilanMasek** [comment]
You are welcome. Not having rights to merge it. We can however push to do so at https://github.com/SeleniumHQ/selenium/issues/4153

**Comment by shs96c** [comment]
Apologies for taking so long to merge this. Thank you for the PR.

**Comment by MilanMasek** [comment]
You are welcome. No worries, glad it's been found useful.

**Pull request merged**
