### PR TITLE
Add structure for Dutch translation and some translations

### PR DESCRIPTION
**Pull request by cambiph**
Added the structure for Dutch translations.
Also translated a couple of pages to Dutch.

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Uh, @cambiph could you please solve the merge conflicts? Then I could merge right away.
Thanks!

**Comment by cambiph** [comment]
I cannot resolve because I do not have write access. Do I create a new pull request where the conflicts are resolved?

**Comment by diemol** [comment]
Yes, exactly, first update your fork and then solve the conflicts there.

**Comment by cambiph** [comment]
I shall close this one as I created a new one.

**Pull request closed without merging**
