### PR TITLE
Proposal for install page to include all supported languages

### PR DESCRIPTION
**Pull request by juperala**
The current installation page only explains installation for Java Maven dependencies. This PR provides proposal including installation steps for all supported languages (java, python, c#, ruby, javascript).

The installation description of Selenium Grid is kept unchanged (although better description for it would be valuable).

Contributor Licence Agreement has been signed.

### CODE REVIEW

**Comment by lmtierney** [comment]
Python for `pip` looks fine, but we may also want to include instructions for using `setup.py`

**Comment by juperala** [comment]
Added alternative Python installation using setup.py.

**Review by hazmeister — APPROVED** [review]

**Review by diemol — APPROVED** [review]

**Comment by diemol** [comment]
Thanks for reviewing @hazmeister!

**Comment by diemol** [comment]
Thanks for your contribution @juperala!

**Pull request merged**
