### PR TITLE
Sample code on homepage for all languages

### PR DESCRIPTION
**Pull request by hazmeister**
Response to feedback on #178 

## Java
image

## Python
image

## C#
image

## Ruby
image

## JavaScript
image

### CODE REVIEW

**Comment by hazmeister** [comment]
Also an option - make python example more fluent:

```from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.expected_conditions import presence_of_element_located

driver = webdriver.Firefox()
wait = WebDriverWait(driver, 10)
try:
    driver.get("http://google.com/ncr")
    driver.find_element_by_name("q").send_keys("cheese" + Keys.RETURN)
    first_result = wait.until(presence_of_element_located((By.CSS_SELECTOR, "h3>a")))
    print(first_result.text)
finally:
    driver.quit()
```

**Comment by cgoldberg** [comment]
since the Python WebDrivers now support the context manager protocol, I think it makes a nice pythonic example to use a `with` statement.  I'd write it as:

```
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


with webdriver.Firefox() as driver:
    driver.get("http://google.com/ncr")
    element = driver.find_element_by_name("q")
    element.send_keys("cheese" + Keys.RETURN)
    wait = WebDriverWait(driver, 10)
    first_result = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "h3>a")))
    print(first_result.text)
```

* browser will quit without needing the try/finally

**Comment by manoj9788** [comment]
@hazmeister are you going to change Python example per @cgoldberg  suggestions?

**Comment by hazmeister** [comment]
@manoj9788 looks good to me - I'll give it a go at home and push the changes up.  Thanks for the suggestion @cgoldberg

**Comment by shs96c** [comment]
@hazmeister, @manoj9788, and @cgoldberg: is this ready to merge?

**Comment by hazmeister** [comment]
I'm happy if everyone else is happy!

**Comment by manoj9788** [comment]
Thanks @hazmeister

**Pull request merged**
