### PR TITLE
Revert "Modify: 1. Commenting note for proper rendering. 2. Updating …

### PR DESCRIPTION
**Pull request by manoj9788**
…code with node async/await statements (#277)"

This reverts commit a255fec53552d7309bb11ef2cae76965aa9b228c.

### CODE REVIEW

**Comment by manoj9788** [comment]
my bad! Ignore this.

**Comment by harsha509** [comment]
Any issue with my PR @manoj9788 ?

**Comment by manoj9788** [comment]
At first, the locator was half done and then realized it was right! and was gonna comment

**Comment by manoj9788** [comment]
I'll fix this. Thanks for your contribution. We will need to alter the locator for other languages too! 
probably next time.

**Comment by harsha509** [comment]
ok @manoj9788. Looking forward to contribute more to selenium. :)

**Comment by manoj9788** [comment]
Most welcome! @Harsha509

**Comment by diemol** [comment]
We don't need to revert that commit, but actually to update the other examples.
The build failures are due to the GitHub API quota when the committers are fetched for the contributors page. That is what we need to fix.

**Comment by manoj9788** [comment]
Thanks, Diego. Exactly told him about updating the other examples! didn't know about the Github Issue.

**Pull request closed without merging**
