### PR TITLE
Update 03_WebDriver.md

### PR DESCRIPTION
**Pull request by cambiph**
Fixed typo

### CODE REVIEW

**Comment by andreastt** [comment]
Did you sign the CLA?

**Comment by cambiph** [comment]
No, what is it and where can I do it?
I just want to cooperate but I can't seem to find any people to teach me how things go around here.

**Comment by jimevans** [comment]
This really should be in the README for this repository, like it is in the README for the main selenium repository. Here is the link to the CLA:

https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0

**Comment by cambiph** [comment]
Ok, will do!
And where can I get info on helping with the documentation besides the generic pages in the seleniumHQ website?
Maybe talk to some other doc writers to see what still needs to be done etc.

**Comment by andreastt** [comment]
@jimevans: Mentioned the CLA in the README in 038d6d8.

**Comment by andreastt** [comment]
Integrated as ef5773cc28678241744e4a7b790eaea9223d091e, thanks for the patch!

When it comes to helping with the documentation, there is no meta documentation for that.  The best approach is to look at the scaffolding we've set up so far but which is lacking content.  Starting by filling out missing sections is probably a good approach.

Also talking to people involved in rewriting the docs (look at the commit list or the AUTHORS file) makes sense.  Most of us hang around in the #selenium IRC channel on Freenode if you want to chat. (-:

Good luck!

**Pull request closed without merging**
