### PR TITLE
Linked all the links from the index page

### PR DESCRIPTION
**Pull request by maeriens**
It was just adding ID's to all the elements. Did not check if they _should_ be linked, just linked.
 I do have some questions regaring markup - as to why pages don't have the html boilerplate code, or why several <p> tags are not closed... should those be checked and corrected?

### CODE REVIEW

**Comment by maeriens** [comment]
@andreastt I saw your comment in https://github.com/SeleniumHQ/docs/pull/134 after doing this Pull Request - not exactly sure what is not working properly

**Comment by andreastt** [comment]
@maeriens What is working properly? If you inspect the DOM, you will see that all headers have IDs.

**Comment by maeriens** [comment]
@andreastt ah - it adds the ID's to the Index page thought it did to the entire site. Thing is, as ID's were not present in the rest of the pages, clicking any link was always redirecting to the top of the required page instead of focusing on the desired section

**Comment by andreastt** [comment]
Clicking ‘Attributions’ from the front page leads me to https://seleniumhq.github.io/docs/attr.html#attributions, which has a `<h2>Attributions</h2>`  in the document that has an ID added through docs.js.

I’d say this patch isn’t necessary.

**Comment by maeriens** [comment]
Wait, you are not seeing the full effect. The idea of that href is to link to an element with an id of `attributions`. This is really clear with the example of clicking https://seleniumhq.github.io/docs/worst.html#link_spidering.
 If you click that link, you will be taken to the Worst Practices page - but not with focus on **Link Spidering** Try this locally; add the ID to the h2 like I did in this branch, and click each link from the main navigation. Observe that it _focuses the user on the header that was clicked._

**Comment by andreastt** [comment]
I don’t understand. If I click ‘Link Spidering’ from the ToC, I am taken to https://seleniumhq.github.io/docs/worst.html#link_spidering which brings that subsection at the bottom of the document into view.

**Comment by maeriens** [comment]
Hm. Weird; it was not working for me on latest Chrome nor latest Firefox. Deleted all cache/cookies for both and it worked. 
This is closed correctly. Sorry for the back-and-forth, thanks for the answers.

**Pull request closed without merging**
