### PR TITLE
Add JS examples to Getting Started page

### PR DESCRIPTION
**Pull request by systemboogie**
This adds some JavaScript examples to the Getting Started page.

I have just signed the CLA.

### CODE REVIEW

**Comment by systemboogie** [comment]
The status of the Travis job doesn't seem to be reported back here, but it seems to have passed: https://travis-ci.org/SeleniumHQ/docs/builds/535347969

**Comment by diemol** [comment]
Yes, it is really strange, I triggered the build manually again and the status is still not reported. I will go through it during the weekend and make it work. Thanks @systemboogie

**Comment by diemol** [comment]
Seems that travis.org is not reporting status anymore, we are in the process of migrating to the GitHub Apps thing for Travis so we can get them back.

**Review by diemol — APPROVED** [review]
Thank you @systemboogie!

**Pull request merged**
