### PR TITLE
Improvements to Grid document.

### PR DESCRIPTION
**Pull request by djangofan**
Reworked the beginning of the Grid document.  Trying to normalize formatting to fall inline with restructured text markup (.rst) , and limited to 72 columns per line.  Lots of work but made some progress.

### CODE REVIEW

**Comment by andreastt** [comment]
Thanks, this looks very good to me! Squashed and integrated as 76c78f385aa9ea27351480f51bd5a81ebb117e93.

**Comment by djangofan** [comment]
Is there a easy way to preview my doc changes without having to build the
project?  Do you have it hosted anywhere? It would help me to normalize my
changes

**Comment by andreastt** [comment]
There is https://github.com/SeleniumHQ/selenium-docs/blob/master/grid.rst but it's not built and hosted anywhere else yet.  I need to fix that.

**Comment by djangofan** [comment]
Are you saying that Github has the ability to render these .rst templates correctly?  I had the impression that "github markdown" rendering will display a different look than the Sphinx translation.  Yes, it would be nice if it were hosted somewhere, even on Github, as the converted-to-html documents.

**Comment by andreastt** [comment]
It doesn't render them correctly, but it renders it for a subset of “correctly”.  So yes, it will look different to the one built by Sphinx.

We can probably host it using gh-pages but it requires a service that periodically pulls the latest changes, builds the documents, and pushes them to that branch.  That shouldn't be hard to set up though.  Good suggestion!

**Pull request closed without merging**
