### PR TITLE
Added dollar sign to distinguish console commands

### PR DESCRIPTION
**Pull request by maeriens**

### CODE REVIEW

**Comment by maeriens** [comment]
@andreastt why was this closed and reopened? Do I need to fix something else, wait for the Travis check to be marked as completed or anything?

**Comment by andreastt** [comment]
I don’t understand why Travis isn’t doing what it’s supposed to. Closing and re-opening retriggers the job, but it doesn’t appear to have helped.

**Comment by maeriens** [comment]
Travis is marking everything as 'abuse detected'? Not sure what that means - never used it before. https://travis-ci.org/SeleniumHQ/docs/requests

**Comment by maeriens** [comment]
...will send a support ticket to Travis - I think it has to do with the thing that I changed my username in github a few months ago.

**Comment by maeriens** [comment]
I contacted Travis and fixed the issues that my github account had with the builds - I retriggered both so now they will be checked 😄

**Comment by andreastt** [comment]
Thanks, merged.

**Pull request merged**
