### PR TITLE
Updated all the test URL's to be consistent 

### PR DESCRIPTION
**Pull request by sri85**
All the URL's should be pointing to `https://` instead of `http://` and also the `ruby` example was using 'http://google.com' instead of `https://google.com/ncr`

### CODE REVIEW

**Review by sri85 — COMMENTED** [review]
Updated the PR to update C# URL

**Review by hazmeister — APPROVED** [review]

**Comment by diemol** [comment]
Thanks for the review @hazmeister!

**Comment by diemol** [comment]
Thanks for your contribution @sri85!

**Comment by sri85** [comment]
Thank you @diemol @hazmeister for reviewing and merging my PR .

**Pull request merged**
