### PR TITLE
Issue 158

### PR DESCRIPTION
**Pull request by ghost**
Hi, I have made a start on the Docker Selenium section.  I don't think it is complete but it gives something to build on.

I wasn't sure if we really need to repeat the instructions from the docker-selenium project as the docs would require constant maintenance.

I have signed the CLA.

### CODE REVIEW

**Comment by diemol** [comment]
I also wanted to use a better documentation for the docker-selenium than the current readme, but I am not sure if this should go here. Perhaps it is better that docker-selenium has its own docs. What do you think @shs96c @manoj9788?

**Comment by manoj9788** [comment]
I second that, good to have docs separate for a docker-selenium project and have Selenium Grid docs to this current docs.

**Comment by diemol** [comment]
After discussing about it with @shs96c, it makes sense to have a reference of the Docker-Selenium project in the official docs, but we should take the time to create the docs for that project.

Thanks for your contribution @nvonop!

**Comment by ghost** [comment]
Great, are you thinking or creating a separate docs repo for the Docker-Selenium project or expanding the Readme and other markdown files?

I am happy to help if I can.

Nick

**Comment by diemol** [comment]
@nvonop yes, the idea would be to have a simple site with the same look & feel as the Selenium ones for the docker-selenium repo. In short, it would be like putting the readme and the Wiki in it.

If you want to give us a hand, we are happy to receive contributions.

**Pull request merged**
