### PR TITLE
added kotlin code examples 

### PR DESCRIPTION
**Pull request by boris779**
Added for all pages kotlin code examples in English,
further added the default text for other supported docs-languages

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Hey, thanks for the PR @boris779!

Before checking it, could you please also add the code to the other languages? (Instead of the placeholders?)

**Comment by boris779** [comment]
Hi @diemol !

You mean, copy the english code-examples to Spanish, Chinese, etc.?

**Comment by diemol** [comment]
Exactly, the code is the same in the end.

**Comment by diemol** [comment]
Hey @boris779, do you think you will be able to make the changes soon? 
I am planning to move this docs into the new site, and I am just waiting for this PR to be merged. If you need a couple of days, that's ok, you can send the PR to the repository of the new site.

**Comment by boris779** [comment]
Hi Diego.
Yes, today I made around 40% of the needed changes. So give me 2-3 days and it will be finished.

**Comment by boris779** [comment]
@diemol finished coping to all languages. I noticed a lot of differences between pages which are not translated (from English)

**Review by diemol — APPROVED** [review]
Thanks @boris779!

**Comment by diemol** [comment]
> @diemol finished coping to all languages. I noticed a lot of differences between pages which are not translated (from English)

Yep, we need to get better in that. Please send us PRs whenever you see something strange.

**Pull request merged**
