### PR TITLE
Add intro snippets for Java and JavaScript

### PR DESCRIPTION
**Pull request by hazmeister**
Added sample scripts for java and javascript on the front page.  The examples should perform exactly the same steps for all three examples.

Switched to using implicit wait because it works well for the example/beginners and using try/catch to ensure the browser clears up after itself (without `quit()` we leave zombie driver processes running, which can be confusing for beginners).

Decided to use use try/catch instead of third party libraries like JUnit.  Let me know your thoughts on this, as typically we wouldn't expect users to write a main class in java to run test code, but I liked the idea of something only using built in components that you could copy from your browser straight into an IDE.

## Java
image

## Python (modified)
image

## Javascript
image

### CODE REVIEW

**Comment by manoj9788** [comment]
Can we try to add an example without Implicit waits?

**Comment by hazmeister** [comment]
We certainly can switch to using explicit wait, which would be recommended for regular use, but I am concerned it makes the sample code more complicated. The line before the code sample reads "Here is one of the simplest instructions you can make:" and I figured implicit wait would demonstrate better given the context.

But.. `WebdriverWait` is an important part of the API.  I'll push up the other examples I wrote so you can see what I mean and we can choose the best one to merge.

**Comment by shs96c** [comment]
Implicit waits are something that almost everyone within the project argue shouldn't be used. Putting it front-and-centre sends a terrible message. @hazmeister, looking forward to those other examples :)

**Comment by hazmeister** [comment]
Those other examples are in #180 @shs96c.  If we document how to use Explicit and Fluent Wait well, perhaps we could deprecate implicit wait in the APIs if they are considered bad practice?  Whilst we are on the subject- the java example in the other PR is using the `ExpectedConditions` library.  Are there plans to follow the C# bindings and push folks to using lambda expressions?

**Comment by hazmeister** [comment]
#180 looks like a better way to go

**Pull request closed without merging**
