### PR TITLE
Documented WebDriver with python code examples

### PR DESCRIPTION
**Pull request by liushilive**
* get_window_size
* set_window_size
* get_window_position
* set_window_position
* maximize_window
* fullscreen_window

### CODE REVIEW

**Comment by lmtierney** [comment]
@diemol thoughts on using the w3c commands instead of legacy? This PR (and the current Java examples) show the OSS way of doing it and do not provide examples using the preferred w3c `get_window_rect` command. Or maybe we provide both? @hazmeister

**Comment by lmtierney** [comment]
Hmm I'm not actually finding a Java command for getting window rect...

**Comment by jimevans** [comment]
@lmtierney That’s because Java doesn’t expose the getWindowRect command by itself. It used the command under the covers for getting window size and position, but doesn’t expose the command to return the whole rect.

**Comment by lmtierney** [comment]
@jimevans Do you know of a reason why we aren't? Did I miss a discussion? The `WebElement` has a `getRect` on it

**Comment by hazmeister** [comment]
Given the large sections of missing contents in the docs, I would vote that we merge this PR for now. There’s nothing stopping someone from adding a second code block with an alternate approach, but for Selenium today this code works. When version 4 ships, this snippet can be easily updated.

**Comment by lmtierney** [comment]
@hazmeister fair point. Thank you for the PR @liushilive!

**Comment by diemol** [comment]
Completely agree with @hazmeister! Thanks for merging @lmtierney

**Pull request merged**
