### PR TITLE
 Issue #141 Anchor tags not working

### PR DESCRIPTION
**Pull request by Ravichandra-C**
Updated the doc.js to automatically load to the selected section.

### CODE REVIEW

**Review by diemol — CHANGES_REQUESTED** [review]
Hi @Ravichandra-C,
Could you please check the comments in #141? I tried the PR and it does not really fix them. 
And sorry for the late review.

**Comment by hazmeister** [comment]
Finally given this a proper go this evening.  Looks like the snippet code is racing the anchor code here, and misbehaving in some browsers.  Firefox seems to work as expected, Safari ends up in roughly the right place, but Chrome seems to end up quite some way away.

**Comment by Ravichandra-C** [comment]
Deigo,

Sure,I'll look into it.

Regards,
Ravi

**Comment by diemol** [comment]
Closing in favour of the new docs UI powered by [Hugo](https://gohugo.io/)

**Pull request closed without merging**
